# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

 ## Looping Through Arrays

In [3]:
#creating a 2D array
arrA = np.array([[11,12,13], [14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
# Loop through the first dimension of arrA
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [9]:
# Loop through the second dimension of arrA
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


# the difference between the first and second are the placements in the outputs, the first output loops it virtually while the second output loops it diagonally

In [10]:
# Loop through the second dimension of arrA
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents the entire row,
# not a single number. Multiplying x by 2 doubles every value
# in the whole row each time the inner loop runs.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [12]:
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])
joined_array_1 = np.concatenate((arrA, arrA))
# printing result
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [14]:
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])

joined_array_2 =np.concatenate((arrA, arrA), axis=1)
# printing result
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [18]:
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])
#concatenate arrA with itself
joined_array_1 = np.concatenate((arrA, arrA))

# stack joined_array_1 with itself
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

# printing result 
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [23]:
# ERROR
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

In [24]:
# i do not get a error message, nor a output of anything

In [26]:


# joining arrA and Joined_array_1
another_joined_array = np.concatenate((arrA, joined_array_1))

# printing reslut
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [29]:
# creating another_2 and joining arrA & joined_array_1
another_2 = np.concatenate((arrA, joined_array_1), axis = 1)
# printing results                          
print(another_2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [30]:
# both arrays do not have the same number of arrays to join with axis=1 causing the error to happen, arrA has 2 rows while joined_array_1 has 4 rows 

In [31]:
#using hstack
another_3 = np.hstack((arrA, arrA))
#printing results
print(another_3)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [ ]:
# by using hstack the function put the unders side-by-side and i got this..
# [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

## Splitting Array

In [32]:
import numpy as np

# Create arrA
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

# Use where() to check for even numbers
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')

# Print result
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [33]:
import numpy as np

# Create arrB
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

# Sort arrB
arrB_sorted = np.sort(arrB)

# Print sorted array
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [34]:
import numpy as np

# Create arrB
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

# Print arrB
print(arrB)

# Find values less than 7
z = arrB < 7

# Filter arrB using z
arrC = arrB[z]

# Print arrC
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [35]:
import numpy as np

# Create arrB
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

# Create filter for values greater than or equal to 7
y = arrB >= 7

# Filter arrB using y
arrD = arrB[y]

# Print arrD
print(arrD)

[ 7 13  7]
