# Exercise 1.B NumPy Random

In [16]:
import numpy as np

## Generating Random Numbers

In [2]:
# creating random integers between 1 and 20 with 2 elements
r_i = np.random.randint(1, 20, size=2)

# printing result
print(r_i)

[1 3]


In [5]:
# creating random intergers between 1 and 20 with 1 row and 2 columns
r_2 = np.random.randint(1, 20 ,size=(1,2))
# printing result
print (r_2)

[[6 7]]


In [6]:
# creating random floats between 0 and 1 with 2 rows and 1 column
r_3 = np.random.rand(2,1)

# printing result
print(r_3)

[[0.73091483]
 [0.68492197]]


In [7]:
# creating random intergers between 20 and 100 with 4 rows and 5 columns
r_4 = np.random.randint(20, 100, size=(4,5))

# print reslut
print(r_4)

[[93 47 88 37 38]
 [63 49 49 55 26]
 [25 24 22 46 76]
 [85 99 23 84 84]]


In [11]:
# creating random floats between 0 and 1 with 4 rows and 5 columns
r_5 = np.random.rand(4,5)
print(r_5)

[[0.28797971 0.09041569 0.96294108 0.34726581 0.32587717]
 [0.86393017 0.27313943 0.83651543 0.04158887 0.20408962]
 [0.18047611 0.1399764  0.04318345 0.82435742 0.69757765]
 [0.44304974 0.64483322 0.65295496 0.61175117 0.61695247]]


## Generating Random Choices from an Array

In [13]:
# create a 1-D array of student names
students = np.array([
    "Ava",
    "Liam",
    "Sophia",
    "Noah",
    "Mia",
    "Elijah",
    "Emma",
    "James",
    "Olivia",
    "Lucas",
    "Charlotte",
    "Benjamin"
])

#print array
print(students)

['Ava' 'Liam' 'Sophia' 'Noah' 'Mia' 'Elijah' 'Emma' 'James' 'Olivia'
 'Lucas' 'Charlotte' 'Benjamin']


In [18]:
# choosing random student name
call_on = np.random.choice(students)

# print chocie
print(call_on)

Sophia


In [19]:
# choosing random students with 3 row and 4 columns 
breakout_groups = np.random.choice(students,size=(3,4))

#print chocies
print(breakout_groups)

[['Olivia' 'Mia' 'Ava' 'Noah']
 ['Sophia' 'Benjamin' 'James' 'Mia']
 ['James' 'Sophia' 'Liam' 'Lucas']]


In [20]:
# no this wouldn't be an effective way for breakout groups becuase some students come up more than once making the group uneven. 

In [23]:
# choosing five random students
call_on_weighted = np.random.choice(students,
                                    size=5,
                                    p=[
    
        0.30,  # Ava has a 30% chance
        0.10,  # Liam has a 10% chance
        0.10,  # Sophia has a 10% chance
        0.08,  # Noah has an 8% chance
        0.07,  # Mia has a 7% chance
        0.07,  # Elijah has a 7% chance
        0.06,  # Emma has a 6% chance
        0.05,  # James has a 5% chance
        0.05,  # Olivia has a 5% chance
        0.05,  # Lucas has a 5% chance
        0.07,  # Charlotte has a 7% chance
        0.00   # Benjamin has a 0% chance (will never be selected)
                                    ]
                                   )
# print choice 
print(call_on_weighted)

['Ava' 'James' 'Elijah' 'Olivia' 'Olivia']


## Generating a Normal Distribution

In [24]:
# normal (bell curve)distribution
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))

# printing reslut
print(bell_curve)

[[ 2.17152369  8.02508093 11.00277342  5.8401242  13.61587018]
 [13.82340923  9.70904278 -1.52756192 10.8302491   6.61901963]
 [11.00085776 10.95142009  8.21569379 12.47636981 13.0301238 ]
 [10.73694585 16.16927711 10.27794087 15.45023878 12.8025868 ]]
